auto: false
auto: true
server: false
lsi: false
pygments: true
permalink: /:title
paginate: 10
exclude: ["Rakefile", "LICENSE.txt", "CNAME"]
title: Unit Grid System
url: http://unitgs.bernardoantunes.com
github_user: bernardoantunes
navigation:
- text: Home
  url: /index.html
- text: Start here
  url: /starthere/index.html
- text: Documentation
  url: /documentation/index.html
  layout: post
- text: Get involved
  url: /getinvolved/index.html